Removing player on click.
DTS-STN/Scrum-Poker pull request #100
Opened 2022-04-08 18:58 UTC by nibivi77

## [DUMS-106](https://jira-dev.bdm-dev.dts-stn.com/browse/DUMS-106) 

### Description
PARTIAL COMPLETION
This PR covers the use case where a player other than the host clicks "leave room"

2022-04-12 12:44 UTC, DaceyTom2 requested changes

2022-04-12 12:44 UTC, DaceyTom2 commented on pages/room/[id].js
> +          (user2) => user2.id === user1.id
Small consideration to rename user1 and user2 as it implies we are looking for 2 different users with the same id

2022-04-12 12:44 UTC, DaceyTom2 commented on pages/room/[id].js
> +      console.log(copiedRoomUserIds)
Remove console log

2022-04-12 12:44 UTC, DaceyTom2 commented on pages/room/[id].js
> +        console.log(e)
The app can handle this error

2022-04-12 12:44 UTC, DaceyTom2 commented on pages/room/[id].js
> +      console.log(
I'm assuming this is a place holder for destroyRoom.
Either remove destroyRoom or call it here and console log the reminder from the placeholder function

2022-04-12 12:44 UTC, DaceyTom2 commented on pages/room/[id].js
> +            onBootClick={removeOnePlayer}
Keep the naming consistent.
Either onClick or onBootClick/OnLeaveRoomClick

2022-04-12 14:24 UTC, DaceyTom2 approved these changes

2022-04-12 14:24 UTC, DaceyTom2 commented on package.json
> +    "react-confirm-alert": "^2.8.0",
This dependency doesn't look promising based off use/issues/PRs https://github.com/GA-MO/react-confirm-alert
I'd flag this for a real app but is fine for prototypes

2022-04-13 13:53 UTC, MarcoGoC approved these changes
Looks good, pending the package

2022-04-13 14:45 UTC, merged