Added client side validation for room creation
DTS-STN/Scrum-Poker pull request #51
Opened 2022-03-17 19:08 UTC by krischarbonneau

## [DUMS-66 - Write validation](https://jira-dev.bdm-dev.dts-stn.com/browse/DUMS-66) (Jira Issue)

### Description

This PR adds validation for creating a new room. Whenever the user clicks the `Create Room` button, there is a first a check to see if the user name is either empty or contains special characters before a room is created. If either of those flags are true, an error label is shown above the text input.

### What to test for/How to test

1. Pull in branch
2. Type `npm run dev`
3. In order to prevent from flooding the server with new rooms, you can comment out lines 56-62 in `home.js`
4. Click create room without entering anything, an error message should show up
5. Enter in `name!` into the text input and click create room, an error message should show up
6. Enter in a valid name and click create room (if you followed step 3 there should be no error but nothing else will happen. without the lines commented you'll be sent to a new room)

2022-03-18 13:19 UTC, DaceyTom2 requested changes

2022-03-18 13:19 UTC, DaceyTom2 commented on pages/home.js
> +  }
Something about this logic isn't working and I'm not sure why.
setValid(false) is setting the state to false but isValid returns true.

Another thing to consider is if the addRoom request fails we can now catch it and display the ErrorLabel component. addRoom was returning a 400 error for bad request (probably some server work that was done) and hanging

2022-03-18 20:50 UTC, DaceyTom2 approved these changes
Looks good

2022-03-21 18:06 UTC, nibivi77 approved these changes
This is great! Thanks !

2022-03-21 18:07 UTC, merged