feat: user is able to show/hide card and apply the change to all user…
DTS-STN/Scrum-Poker pull request #66
Opened 2022-03-28 15:00 UTC by alexunique0519

…s in the same room

##[DUMS-75](https://jira-dev.bdm-dev.dts-stn.com/browse/DUMS-75)
##[DUMS-77](https://jira-dev.bdm-dev.dts-stn.com/browse/DUMS-77)

### Description
On the client side, user could click to show/hide button to call mutations to change the current card' show/hide status. 

List of proposed changes:

-
-

### What to test for/How to test

### Additional Notes

2022-03-29 14:48 UTC, krischarbonneau requested changes

2022-03-29 14:48 UTC, krischarbonneau commented on pages/room/[id].js
> +  const [showHideCard] = useMutation(UPDATE_ROOM)
```suggestion
  const [updateRoom] = useMutation(UPDATE_ROOM)
```

This should be more generic as we'll likely be using this mutation for other features

2022-03-29 15:04 UTC, DaceyTom2 requested changes
Couple of things. Let me know if you want to set up a call to go over them as they are hard to explain with typing

2022-03-29 15:04 UTC, DaceyTom2 commented on pages/room/[id].js
> +    const usersIDList = []
Rework this to use the room data. users and room might become inconsistent. Also this constantly adds the current user to the end of the users list ie [ 1, 2, 3, 1, 1, 1, 1]

2022-03-30 12:18 UTC, DaceyTom2 commented
Big improvement!

2022-03-30 13:39 UTC, DaceyTom2 approved these changes

2022-03-30 13:53 UTC, krischarbonneau approved these changes

2022-03-30 13:54 UTC, merged