Redirecting users
DTS-STN/Scrum-Poker pull request #76
Opened 2022-03-30 16:57 UTC by nibivi77

## [DUMS-81](https://jira-dev.bdm-dev.dts-stn.com/browse/DUMS-81)

### Description

Redirecting users for:
 - Joining a room without going through the form on the home page.
 - Using the URL bar to join a room, existing or not.
 - Joining a room id that does not exist from the home page form.

### What to test for/How to test

Create a room from a browser.
Open a new browser and try joining the room from the URL. `localhost:3000/room/roomid`

Try joining a non-existing room both from the URL and the join form on the home page.

### Additional Notes

2022-03-31 13:17 UTC, MarcoGoC reviewed
![image](https://user-images.githubusercontent.com/52539578/161063591-c1bc1ccb-73cb-405e-9d31-efdd21a1bc1a.png)
to reproduce:
deleted all the cookies
tried to join a non existing room.
created a new room
page loads with the warning above

2022-03-31 14:35 UTC, DaceyTom2 requested changes

2022-03-31 14:35 UTC, DaceyTom2 commented on pages/home.js
> +      {router.query.error ? (
This is a bit quirky and a security risk.
Perhaps try returning error=true or an error code in the query string.

Then set the error message to something generic

2022-04-04 15:28 UTC, krischarbonneau commented on pages/home.js
> +      ) : undefined}
Great job! Mostly nitpicking as I think this looks pretty good so I'll approve but I think the error label could use a bit of bottom padding. Something like this:

```suggestion
      {queryErrorCode ? (
      <div className="pb-4">
          <ErrorLabel message={errorCodeMsg}></ErrorLabel>
       </div>
      ) : undefined}
```

2022-04-04 15:28 UTC, krischarbonneau approved these changes

2022-04-05 14:38 UTC, merged